Fix deploy workflow agaia

diff --git a/.github/workflows/deploy-to-test.yml b/.github/workflows/deploy-to-test.yml
--- a/.github/workflows/deploy-to-test.yml
+++ b/.github/workflows/deploy-to-test.yml
@@ -8,14 +8,26 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # Step 1: Checkout Dev_ADAP code
       - name: Checkout Dev Repo
         uses: actions/checkout@v4
+        with:
+          persist-credentials: false   # IMPORTANT
 
-      - name: Push to Test_ADAP (Mirror)
+      # Step 2: Debug (check token)
+      - name: Debug Token
         run: |
+          if [ -z "${{ secrets.TARGET_REPO_TOKEN }}" ]; then
+            echo "TOKEN NOT FOUND ❌"
+            exit 1
+          else
+            echo "TOKEN FOUND ✅"
+          fi
 
+      # Step 3: Push to Test_ADAP
+      - name: Push to Test_ADAP
+        run: |
           git config --global user.name "github-actions"
-
           git config --global user.email "actions@github.com"
 
-          git push https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/Sherikk786/Test_ADAP.git --mirror
+          git push https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/Sherikk786/Test_ADAP.git HEAD:main --force
